# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-DNS
version:      0.98
version_from: DNS.pm
installdirs:  site
requires:
    Net::DNS:                      0.12
    POE:                           0.11
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
