--- #YAML:1.0
name:                POE-Component-Client-DNS
version:             0.99
abstract:            Non-blocking/concurrent DNS queries using Net::DNS and POE
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
    Net::DNS:                      0.53
    POE:                           0.31
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
