--- #YAML:1.0
name:               POE-Component-Client-DNS
version:            1.04
abstract:           Non-blocking/concurrent DNS queries using Net::DNS and POE
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::DNS:    0.59
    POE:         1.007
    Test::More:  0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://thirdlobe.com/svn/poco-client-dns/trunk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
